name: Publish Package to NPM

on:
  push:
    branches:
      - main
      - master

jobs:
  publish:
    name: 发布新版本
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set node env
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - name: Install
        run: |
          npm i -g pnpm
          pnpm install
          npm run build
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > .npmrc
          npm publish --access public
